### ISSUE TITLE
PHP 7.1.4, 7.0.18 - Fixed bug (on non-blocking SSL sockets)

### ISSUE THREAD

**Issue by MegaBedder** [cubiclesoft/net-test#1]
**PHP** [7.1.4](http://php.net/ChangeLog-7.php#7.1.4), [7.0.18](http://php.net/ChangeLog-7.php#7.0.18)
**OpenSSL**: Fixed bug #[72333](https://bugs.php.net/bug.php?id=72333) (fwrite() on non-blocking SSL sockets doesn't work).

https://github.com/cubiclesoft/net-test/blob/ff389ca436f5487bcca5c6ab13188dd7f69e9f44/support/generic_server.php#L279

```php
if ($this->ssl)
{
	// This is a huge hack that has a pretty good chance of blocking on the socket.
	// Peeling off up to just 4KB at a time helps to minimize that possibility.  It's better than guaranteed failure of the socket though.
	@stream_set_blocking($client->fp, 1);
	$result = fwrite($client->fp, (strlen($client->writedata) > 4096 ? substr($client->writedata, 0, 4096) : $client->writedata));
	@stream_set_blocking($client->fp, 0);
}
```

**Comment by cubiclesoft** [comment]
I'm going to guess that you noticed who actually opened that issue on the PHP bug tracker and subsequently closed this issue.  If you are trying to say that the code should be limited to specific PHP versions because it's been fixed or to remove the code altogether, then those could be possibilities to discuss.  I considered it during my most recent refactoring.  By the way, the bug was fixed in 7.1.4, not 7.1.22 as linked.

The particular code snippet is found across multiple CubicleSoft product lines.  The primary source for it is Ultimate Web Scraper Toolkit, which is where I first encountered the bug and first introduced the patch.  The `GenericServer` class is part of `php-misc`.  This repo (net-test) is pretty far downstream.
